// <auto-generated />
namespace HBShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _5th : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_5th));
        
        string IMigrationMetadata.Id
        {
            get { return "201409221728344_5th"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
